

#ifndef _UNITTEST_CONFIGURE_H
#define _UNITTEST_CONFIGURE_H

#cmakedefine FILESYSTEM_TESTDIR "@FILESYSTEM_TESTDIR@"
#cmakedefine DICOMIMAGE_IMAGEDIR "@DICOMIMAGE_IMAGEDIR@"
#cmakedefine SAMPLEANALYSISXML_FILE "@SAMPLEANALYSISXML_FILE@"
#cmakedefine SAMPLEANNOTATION_FILE "@SAMPLEANNOTATION_FILE@"
#cmakedefine SAMPLEIMAGES_FILE "@SAMPLEIMAGES_FILE@"

#endif