SET( APP_SRCS
src/cmgui/utilities.cpp
src/AnnotationEditor.cpp
src/AnnotationWindow.cpp
src/capclientapp.cpp
src/CAPAnnotationFile.cpp
src/CAPContour.cpp
src/CAPHtmlWindow.cpp
src/CAPMaterial.cpp
src/CAPModelLVPS4X4.cpp
src/CAPModeller.cpp
src/CAPModellingMode.cpp
src/CAPTimeSmoother.cpp
src/CAPXMLFile.cpp
src/CAPXMLFileHandler.cpp
src/cmguicallbacks.cpp
src/CmguiExtensions.cpp
src/CmguiImageSliceGraphics.cpp
src/cmguipanel.cpp
src/DICOMImage.cpp
src/DataPoint.cpp
src/FileSystem.cpp
src/imagebrowser.cpp
src/imagebrowserwindow.cpp
src/ImageSet.cpp
src/ImageSlice.cpp
src/capclientwindow.cpp
src/PlatformInfo.cpp
src/capclient.cpp
)
